-- Hyprland Lua entrypoint (hypr4 / Jules3182 aesthetic)

require("lua.env")
require("lua.monitors")
require("lua.autostart")
require("lua.settings")
require("lua.appearance")
require("lua.animations")
require("lua.binds")
require("lua.rules")
